<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-T4E0KMB" failures="1" tests="2" name="Default test(failed)" time="0.167" errors="0" timestamp="2022-12-19T22:13:33 IST">
  <testcase classname="TestNGPracties.TestNgRetryFailedDemo" name="test3" time="0.039">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGPracties.TestNgRetryFailedDemo.test3(TestNgRetryFailedDemo.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="TestNGPracties.TestNgRetryFailedDemo" name="test2" time="0.011"/>
  <testcase classname="TestNGPracties.TestNgRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
